#!/usr/bin/env python3
"""Generate bounded Prometheus metrics from the reviewed Phase 8 summary."""

from __future__ import annotations

import argparse
from datetime import datetime
import json
from pathlib import Path
import sys
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / "benchmarks" / "phase-08" / "results" / "summary.json"
OUTPUT = (
    ROOT / "charts" / "cn5g-observability" / "files" / "phase08-reviewed.prom"
)
COMPONENTS = ("amf", "smf", "upf")
STATISTICS = (
    "minimum",
    "median",
    "p95_nearest_rank",
    "maximum",
    "sample_standard_deviation",
)
BOUNDARIES = (
    ("mttd_seconds", "detection"),
    ("replacement_ready_seconds", "pod_ready"),
    ("mttr_seconds", "service_recovery"),
    ("user_plane_disruption_seconds", "user_plane_disruption"),
)


def metric_number(value: float | int) -> str:
    return format(float(value), ".15g")


def label_value(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace("\n", "\\n").replace('"', '\\"')


def sample(name: str, value: float | int, **labels: object) -> str:
    if labels:
        rendered = ",".join(
            f'{key}="{label_value(labels[key])}"' for key in sorted(labels)
        )
        return f"{name}{{{rendered}}} {metric_number(value)}"
    return f"{name} {metric_number(value)}"


def family(name: str, help_text: str, samples: Iterable[str]) -> list[str]:
    return [f"# HELP {name} {help_text}", f"# TYPE {name} gauge", *samples, ""]


def validate_summary(data: dict) -> None:
    campaign = data.get("campaign", {})
    contract = data.get("contract", {})
    components = data.get("components", {})
    if data.get("schema_version") != 1:
        raise ValueError("unsupported Phase 8 summary schema")
    if campaign.get("status") != "reviewed_complete":
        raise ValueError("Phase 8 campaign is not reviewed_complete")
    if campaign.get("accepted_attempt_count") != 9:
        raise ValueError("Phase 8 summary must contain nine accepted attempts")
    if tuple(contract.get("components", [])) != COMPONENTS:
        raise ValueError("Phase 8 components differ from the accepted contract")
    if contract.get("repetitions") != 3:
        raise ValueError("Phase 8 repetition count differs from the accepted contract")
    if tuple(components) != COMPONENTS:
        raise ValueError("Phase 8 component summary is incomplete or unordered")
    for component in COMPONENTS:
        summary = components[component]
        if summary.get("repetitions") != 3:
            raise ValueError(f"{component} does not contain three repetitions")
        if summary.get("automatic_recoveries") != 0:
            raise ValueError(f"{component} automatic recovery count changed")
        if summary.get("operator_assisted_recoveries") != 3:
            raise ValueError(f"{component} assisted recovery count changed")
        for source, _ in BOUNDARIES:
            values = summary.get(source, {})
            if tuple(values) != (
                "maximum",
                "mean",
                "median",
                "minimum",
                "p95_nearest_rank",
                "sample_standard_deviation",
            ):
                raise ValueError(f"{component} {source} statistics are incomplete")


def render(data: dict) -> str:
    validate_summary(data)
    campaign = data["campaign"]
    contract = data["contract"]
    components = data["components"]
    completed = datetime.fromisoformat(campaign["completed_at"].replace("Z", "+00:00"))

    lines = [
        "# Generated by scripts/generate-phase08-dashboard-metrics.py.",
        "# Source: benchmarks/phase-08/results/summary.json (reviewed evidence only).",
        "# These gauges describe one completed local recovery campaign; they are not live availability metrics.",
        "",
    ]
    lines += family(
        "cn5g_phase08_reviewed_campaign_info",
        "Identity and review state of the accepted local Phase 8 campaign.",
        [
            sample(
                "cn5g_phase08_reviewed_campaign_info",
                1,
                campaign_id=campaign["campaign_id"],
                status=campaign["status"],
            )
        ],
    )
    for name, help_text, value in (
        (
            "cn5g_phase08_reviewed_accepted_conditions",
            "Number of accepted component and repetition conditions.",
            campaign["accepted_attempt_count"],
        ),
        (
            "cn5g_phase08_reviewed_repetitions",
            "Accepted repetitions per faulted component.",
            contract["repetitions"],
        ),
        (
            "cn5g_phase08_reviewed_completed_timestamp_seconds",
            "Unix timestamp when the reviewed campaign completed.",
            completed.timestamp(),
        ),
    ):
        lines += family(name, help_text, [sample(name, value)])

    boundaries: list[str] = []
    outcomes: list[str] = []
    target_down: list[str] = []
    for component in COMPONENTS:
        summary = components[component]
        for source, boundary in BOUNDARIES:
            for statistic in STATISTICS:
                boundaries.append(
                    sample(
                        "cn5g_phase08_reviewed_recovery_boundary_seconds",
                        summary[source][statistic],
                        boundary=boundary,
                        component=component,
                        statistic=statistic,
                    )
                )
        outcomes.extend(
            (
                sample(
                    "cn5g_phase08_reviewed_recovery_outcomes_total",
                    summary["automatic_recoveries"],
                    component=component,
                    mode="automatic",
                ),
                sample(
                    "cn5g_phase08_reviewed_recovery_outcomes_total",
                    summary["operator_assisted_recoveries"],
                    component=component,
                    mode="operator_assisted",
                ),
            )
        )
        target_down.append(
            sample(
                "cn5g_phase08_reviewed_prometheus_target_down_observations_total",
                summary["prometheus_target_down_observations"],
                component=component,
            )
        )

    lines += family(
        "cn5g_phase08_reviewed_recovery_boundary_seconds",
        "Reviewed fault detection, replacement readiness, service recovery, or user-plane disruption duration in seconds.",
        boundaries,
    )
    lines += family(
        "cn5g_phase08_reviewed_recovery_outcomes_total",
        "Accepted recovery attempts grouped by component and observed recovery mode.",
        outcomes,
    )
    lines += family(
        "cn5g_phase08_reviewed_prometheus_target_down_observations_total",
        "Accepted attempts in which Prometheus observed the faulted component target down.",
        target_down,
    )
    lines += family(
        "cn5g_phase08_reviewed_baseline_restorations_total",
        "Accepted attempts that ended with the complete Phase 5 and Phase 6 baseline restored.",
        [sample("cn5g_phase08_reviewed_baseline_restorations_total", 9)],
    )
    lines += family(
        "cn5g_phase08_reviewed_mongodb_pvc_preserved",
        "Whether every accepted attempt preserved the MongoDB PersistentVolumeClaim identity.",
        [sample("cn5g_phase08_reviewed_mongodb_pvc_preserved", 1)],
    )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated metric file")
    mode.add_argument("--check", action="store_true", help="verify the tracked file is current")
    args = parser.parse_args()

    try:
        generated = render(json.loads(SUMMARY.read_text(encoding="utf-8")))
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f"error: cannot generate Phase 8 dashboard metrics: {error}", file=sys.stderr)
        return 1

    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"phase08_dashboard_metrics=written path={OUTPUT.relative_to(ROOT)}")
        return 0

    try:
        current = OUTPUT.read_text(encoding="utf-8")
    except OSError as error:
        print(f"error: generated Phase 8 dashboard metrics are absent: {error}", file=sys.stderr)
        return 1
    if current != generated:
        print(
            "error: Phase 8 dashboard metrics differ from the reviewed summary; run with --write",
            file=sys.stderr,
        )
        return 1
    print("phase08_dashboard_metrics=pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
