#!/usr/bin/env python3
"""Generate bounded Prometheus metrics from the reviewed Phase 7 summary."""

from __future__ import annotations

import argparse
from datetime import datetime
import json
from pathlib import Path
import sys
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / "benchmarks" / "phase-07" / "results" / "summary.json"
OUTPUT = (
    ROOT / "charts" / "cn5g-observability" / "files" / "phase07-reviewed.prom"
)
LEVELS = ("1", "3", "5")
STATISTICS = (
    "minimum",
    "median",
    "p95_nearest_rank",
    "maximum",
    "sample_standard_deviation",
)


def metric_number(value: float | int) -> str:
    return format(float(value), ".15g")


def label_value(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace("\n", "\\n").replace('"', '\\"')


def sample(name: str, value: float | int, **labels: object) -> str:
    if labels:
        rendered = ",".join(
            f'{key}="{label_value(labels[key])}"' for key in sorted(labels)
        )
        return f"{name}{{{rendered}}} {metric_number(value)}"
    return f"{name} {metric_number(value)}"


def family(name: str, help_text: str, samples: Iterable[str]) -> list[str]:
    return [f"# HELP {name} {help_text}", f"# TYPE {name} gauge", *samples, ""]


def statistics(
    name: str,
    values: dict[str, float | int],
    scale: float = 1.0,
    **labels: object,
) -> list[str]:
    return [
        sample(name, values[statistic] * scale, statistic=statistic, **labels)
        for statistic in STATISTICS
    ]


def validate_summary(data: dict) -> None:
    campaign = data.get("campaign", {})
    contract = data.get("contract", {})
    if data.get("schema_version") != 1:
        raise ValueError("unsupported Phase 7 summary schema")
    if campaign.get("status") != "reviewed_complete":
        raise ValueError("Phase 7 campaign is not reviewed_complete")
    attempts = campaign.get("accepted_attempts", [])
    if campaign.get("accepted_attempt_count") != 9 or len(attempts) != 9:
        raise ValueError("Phase 7 summary must contain nine accepted attempts")
    if tuple(str(item) for item in contract.get("ue_levels", [])) != LEVELS:
        raise ValueError("Phase 7 UE levels differ from the accepted contract")
    if contract.get("repetitions") != 3:
        raise ValueError("Phase 7 repetition count differs from the accepted contract")
    if tuple(sorted(data.get("per_level", {}), key=int)) != LEVELS:
        raise ValueError("Phase 7 per-level summary is incomplete")
    if tuple(sorted(data.get("resources", {}), key=int)) != LEVELS:
        raise ValueError("Phase 7 resource summary is incomplete")


def render(data: dict) -> str:
    validate_summary(data)
    campaign = data["campaign"]
    contract = data["contract"]
    per_level = data["per_level"]
    resource_levels = data["resources"]
    completed = datetime.fromisoformat(campaign["completed_at"].replace("Z", "+00:00"))

    lines = [
        "# Generated by scripts/generate-phase07-dashboard-metrics.py.",
        "# Source: benchmarks/phase-07/results/summary.json (reviewed evidence only).",
        "# These gauges describe one completed local experiment; they are not live capacity metrics.",
        "",
    ]
    lines += family(
        "cn5g_phase07_reviewed_campaign_info",
        "Identity and review state of the accepted local Phase 7 campaign.",
        [
            sample(
                "cn5g_phase07_reviewed_campaign_info",
                1,
                campaign_id=campaign["campaign_id"],
                status=campaign["status"],
            )
        ],
    )
    scalar_families = (
        (
            "cn5g_phase07_reviewed_accepted_conditions",
            "Number of accepted repetition and UE-level conditions.",
            campaign["accepted_attempt_count"],
        ),
        (
            "cn5g_phase07_reviewed_repetitions",
            "Accepted repetitions per UE level.",
            contract["repetitions"],
        ),
        (
            "cn5g_phase07_reviewed_measurement_duration_seconds",
            "Measured iperf3 interval after warm-up in seconds.",
            contract["measurement_seconds"],
        ),
        (
            "cn5g_phase07_reviewed_warm_up_duration_seconds",
            "Excluded iperf3 warm-up duration in seconds.",
            contract["warm_up_seconds"],
        ),
        (
            "cn5g_phase07_reviewed_idle_baseline_duration_seconds",
            "Observed idle baseline duration in seconds.",
            campaign["idle_baseline_seconds"],
        ),
        (
            "cn5g_phase07_reviewed_completed_timestamp_seconds",
            "Unix timestamp when the reviewed campaign completed.",
            completed.timestamp(),
        ),
    )
    for name, help_text, value in scalar_families:
        lines += family(name, help_text, [sample(name, value)])

    success: list[str] = []
    restarts: list[str] = []
    throughput: list[str] = []
    retransmissions: list[str] = []
    target_attainment: list[str] = []
    fairness: list[str] = []
    icmp_rtt: list[str] = []
    udp_loss: list[str] = []
    udp_jitter: list[str] = []
    procedure_latency: list[str] = []

    for level in LEVELS:
        summary = per_level[level]
        metrics = summary["metrics"]
        success.extend(
            (
                sample(
                    "cn5g_phase07_reviewed_procedure_success_ratio",
                    summary["registration_success_rate_percent"] / 100,
                    procedure="registration",
                    ue_level=level,
                ),
                sample(
                    "cn5g_phase07_reviewed_procedure_success_ratio",
                    summary["pdu_session_success_rate_percent"] / 100,
                    procedure="pdu_session",
                    ue_level=level,
                ),
            )
        )
        restarts.append(
            sample(
                "cn5g_phase07_reviewed_new_restarts",
                summary["new_restarts"],
                ue_level=level,
            )
        )
        for source, direction, scope in (
            ("tcp_forward_aggregate_mbps", "forward", "aggregate"),
            ("tcp_forward_per_ue_median_mbps", "forward", "per_ue_median"),
            ("tcp_reverse_aggregate_mbps", "reverse", "aggregate"),
            ("udp_aggregate_mbps", "udp", "aggregate"),
        ):
            throughput += statistics(
                "cn5g_phase07_reviewed_throughput_bits_per_second",
                metrics[source],
                1_000_000,
                direction=direction,
                scope=scope,
                ue_level=level,
            )
        for source, direction in (
            ("tcp_forward_retransmits", "forward"),
            ("tcp_reverse_retransmits", "reverse"),
        ):
            retransmissions += statistics(
                "cn5g_phase07_reviewed_tcp_retransmissions",
                metrics[source],
                direction=direction,
                ue_level=level,
            )
        for source, traffic in (
            ("tcp_reverse_target_attainment_percent", "tcp_reverse"),
            ("udp_target_attainment_percent", "udp"),
        ):
            target_attainment += statistics(
                "cn5g_phase07_reviewed_target_attainment_ratio",
                metrics[source],
                0.01,
                traffic=traffic,
                ue_level=level,
            )
        fairness += statistics(
            "cn5g_phase07_reviewed_jain_fairness_ratio",
            metrics["tcp_forward_jain_fairness"],
            ue_level=level,
        )
        icmp_rtt += statistics(
            "cn5g_phase07_reviewed_icmp_rtt_seconds",
            metrics["icmp_rtt_average_ms"],
            0.001,
            ue_level=level,
        )
        udp_loss += statistics(
            "cn5g_phase07_reviewed_udp_loss_ratio",
            metrics["udp_loss_percent_max"],
            0.01,
            ue_level=level,
        )
        udp_jitter += statistics(
            "cn5g_phase07_reviewed_udp_jitter_seconds",
            metrics["udp_jitter_ms_p95"],
            0.001,
            ue_level=level,
        )
        for source, procedure, estimator in (
            ("registration_latency_median_ms", "registration", "condition_median"),
            ("registration_latency_p95_ms", "registration", "condition_p95"),
            ("pdu_session_latency_median_ms", "pdu_session", "condition_median"),
            ("pdu_session_latency_p95_ms", "pdu_session", "condition_p95"),
        ):
            procedure_latency += statistics(
                "cn5g_phase07_reviewed_procedure_latency_seconds",
                metrics[source],
                0.001,
                estimator=estimator,
                procedure=procedure,
                ue_level=level,
            )

    lines += family(
        "cn5g_phase07_reviewed_procedure_success_ratio",
        "Successful procedures divided by attempted procedures in accepted conditions.",
        success,
    )
    lines += family(
        "cn5g_phase07_reviewed_new_restarts",
        "New container restarts observed in accepted conditions.",
        restarts,
    )
    lines += family(
        "cn5g_phase07_reviewed_throughput_bits_per_second",
        "Reviewed delivered traffic rate by UE level and statistic.",
        throughput,
    )
    lines += family(
        "cn5g_phase07_reviewed_tcp_retransmissions",
        "Reviewed TCP retransmissions by direction, UE level, and statistic.",
        retransmissions,
    )
    lines += family(
        "cn5g_phase07_reviewed_target_attainment_ratio",
        "Delivered service load divided by offered service load.",
        target_attainment,
    )
    lines += family(
        "cn5g_phase07_reviewed_jain_fairness_ratio",
        "Jain fairness index for forward TCP per-UE throughput.",
        fairness,
    )
    lines += family(
        "cn5g_phase07_reviewed_icmp_rtt_seconds",
        "Reviewed average ICMP round-trip time in seconds.",
        icmp_rtt,
    )
    lines += family(
        "cn5g_phase07_reviewed_udp_loss_ratio",
        "Maximum reviewed UDP packet-loss ratio.",
        udp_loss,
    )
    lines += family(
        "cn5g_phase07_reviewed_udp_jitter_seconds",
        "Reviewed per-condition p95 UDP jitter in seconds.",
        udp_jitter,
    )
    lines += family(
        "cn5g_phase07_reviewed_procedure_latency_seconds",
        "Reviewed registration or PDU-session latency in seconds.",
        procedure_latency,
    )

    cpu: list[str] = []
    memory: list[str] = []
    for level in LEVELS:
        for component in sorted(resource_levels[level]):
            resource = resource_levels[level][component]
            cpu += statistics(
                "cn5g_phase07_reviewed_component_cpu_peak_cores",
                resource["cpu_peak_millicores"],
                0.001,
                component=component,
                ue_level=level,
            )
            memory += statistics(
                "cn5g_phase07_reviewed_component_memory_peak_bytes",
                resource["memory_peak_mib"],
                1024 * 1024,
                component=component,
                ue_level=level,
            )
    lines += family(
        "cn5g_phase07_reviewed_component_cpu_peak_cores",
        "Reviewed per-condition component CPU peak in cores.",
        cpu,
    )
    lines += family(
        "cn5g_phase07_reviewed_component_memory_peak_bytes",
        "Reviewed per-condition component working-set memory peak in bytes.",
        memory,
    )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated metric file")
    mode.add_argument("--check", action="store_true", help="verify the tracked file is current")
    args = parser.parse_args()

    try:
        generated = render(json.loads(SUMMARY.read_text(encoding="utf-8")))
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f"error: cannot generate Phase 7 dashboard metrics: {error}", file=sys.stderr)
        return 1

    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"phase07_dashboard_metrics=written path={OUTPUT.relative_to(ROOT)}")
        return 0

    try:
        current = OUTPUT.read_text(encoding="utf-8")
    except OSError as error:
        print(f"error: generated Phase 7 dashboard metrics are absent: {error}", file=sys.stderr)
        return 1
    if current != generated:
        print(
            "error: Phase 7 dashboard metrics differ from the reviewed summary; run with --write",
            file=sys.stderr,
        )
        return 1
    print("phase07_dashboard_metrics=pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
